{prefix}/include/c++/v1/__config_site
{prefix}/lib/libc++.1.0.dylib
{prefix}/lib/libc++.1.dylib
{prefix}/lib/libc++.dylib
{prefix}/lib/libc++.modules.json
{prefix}/lib/libc++abi.1.0.dylib
{prefix}/lib/libc++abi.1.dylib
{prefix}/lib/libc++abi.dylib
{prefix}/lib/libunwind.1.0.dylib
{prefix}/lib/libunwind.1.dylib
{prefix}/lib/libunwind.dylib
{prefix}/lib/clang/{version_major}/lib/darwin/libclang_rt.osx.a
