{prefix}/bin/clang
{prefix}/bin/clang-{version_major}
{prefix}/bin/clang-apply-replacements
{prefix}/bin/clang-cpp
{prefix}/bin/clang-format
{prefix}/bin/clang-tidy
{prefix}/bin/clang++
{prefix}/bin/clangd
{prefix}/bin/git-clang-format
{prefix}/bin/ld.lld
{prefix}/bin/ld64.lld
{prefix}/bin/lld
{prefix}/bin/llvm-ar
{prefix}/bin/llvm-as
{prefix}/bin/llvm-config
{prefix}/bin/llvm-cov
{prefix}/bin/llvm-cxxfilt
{prefix}/bin/llvm-dwp
{prefix}/bin/llvm-lib
{prefix}/bin/llvm-libtool-darwin
{prefix}/bin/llvm-nm
{prefix}/bin/llvm-objcopy
{prefix}/bin/llvm-objdump
{prefix}/bin/llvm-profdata
{prefix}/bin/llvm-ranlib
{prefix}/bin/llvm-readelf
{prefix}/bin/llvm-readobj
{prefix}/bin/llvm-strip
{prefix}/bin/llvm-symbolizer
{prefix}/include/__libunwind_config.h
{prefix}/include/{triple}/
{prefix}/include/c++/
{prefix}/include/libunwind.h
{prefix}/include/libunwind.modulemap
{prefix}/include/unwind_arm_ehabi.h
{prefix}/include/unwind.h
{prefix}/lib/{triple}
{prefix}/lib/clang/